server:
  port: 8080

spring:
  application:
    name: seckill

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345

  cache:
    type: redis
    redis:
      # 缓存时间
      time-to-live: 60000
      # 是否允许为空
      cache-null-values: false

  redis:
    # redis数据库编号，存在0~15共16个数据库
    database: 0
    # redis服务器IP
    host: 192.168.59.128
    # redis端口号
    port: 6379
    password:
    # redis请求超时时间，超过此值redis自动断开连接
    timeout: 10000ms
    jedis:
      pool:
        # jedis最大连接数，超过此值则提示获取不到连接异常
        max-active: 32
        # jedis最大等待连接数
        max-idle: 32
        # jedis最小等待连接数
        min-idle: 0
        # jedis最大等待时间，超过此值会提示连接超时异常
        max-wait: 10000ms

  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.seckill.entity
